name: build Momizu Preview

on: 
  push:
    branches:
      - '*test'

jobs:
  macos1007-1008:
    name: build for macOS 10.7-10.8
    runs-on: macos-15
    if: ${{ !endsWith(github.event.head_commit.message, 'DONTBUILD') && !contains(github.event.head_commit.message, 'IGNORE10071008') && contains(github.event.head_commit.message, 'BUILDMOMIZU')}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          submodules: true
      
      - name: Restore cached sccache
        id: restore-sccache-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/Library/Caches/Mozilla.sccache 
          key: ${{ runner.os }}-ld64-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ld64-
      
      - name: Restore cached mozbuild toolchains
        id: restore-mozbuild-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/.mozbuild
          key: ${{ runner.os }}-mozbuild-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-mozbuild-
      
      - name: Bootstrap build deps
        id: bootstrap-build-deps
        run: |
          if [ ! -d "$HOME/.mozbuild" ]; then
            echo "Cached .mozbuild toolchain not found. Starting bootstrap..."
            /usr/bin/python3 ./mach bootstrap --application-choice=browser
        
            # Create temp folder to save necessary toolchains
            mkdir -p ~/tmp_toolchains
            
            # Move necessary toolchains outside
            [ -d "$HOME/.mozbuild/node" ] && mv "$HOME/.mozbuild/node" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sccache" ] && mv "$HOME/.mozbuild/sccache" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/cbindgen" ] && mv "$HOME/.mozbuild/cbindgen" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/clang" ] && mv "$HOME/.mozbuild/clang" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sysroot-wasm32-wasi" ] && mv "$HOME/.mozbuild/sysroot-wasm32-wasi" ~/tmp_toolchains/
            
            # Purge old .mozbuild
            rm -rf "$HOME/.mozbuild"
        
            # Rename to (new) .mozbuild
            mv ~/tmp_toolchains "$HOME/.mozbuild"
            
            # echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, nasm, dump_syms, clang, sysroot-wasm32-wasi"
            echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, clang, sysroot-wasm32-wasi"
          fi

          # Install nasm from Homebrew
          brew install nasm
      
      - name: Saving mozbuild toolchain cache
        id: save-mozbuild-cache
        if: steps.restore-mozbuild-cache.outputs.cache-matched-key == ''
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          key: ${{ runner.os }}-mozbuild-${{ github.run_id }}
          path: ~/.mozbuild

      - name: Bootstrap Rust toolchain
        id: bootstrap-rust
        run: |
          export RUST_VERSION=1.82.0
          if [ ! -d "$HOME/.rustup/toolchains/${RUST_VERSION}-custom-aarch64" ]; then
            echo "Cached Rust ${RUST_VERSION}-custom-aarch64 not found. Starting bootstrap..."
            curl -L https://github.com/aobaharuki2005/rust/releases/download/${RUST_VERSION}-custom/${RUST_VERSION}-custom-aarch64.zip -o ${RUST_VERSION}-custom-aarch64.zip
            mkdir -p ~/.rustup/toolchains
            unzip -q ${RUST_VERSION}-custom-aarch64.zip -d ~/.rustup/toolchains
            echo "Bootstrap Rust ${RUST_VERSION}-custom-aarch64 finished."
          fi
        
          # Change default Rust toolchain
          rustup default ${RUST_VERSION}-custom-aarch64
          rustup override set ${RUST_VERSION}-custom-aarch64

          # Verify Rust installation
          cargo --version
          rustc --version
      
      - name: Create mozconfig build config from template
        run: ln -sf ./mozconfig-cicd_1007-1008-momizu.sh .mozconfig
      
      - name: Configure build options
        run: /usr/bin/python3 ./mach configure

      - name: Build
        run: /usr/bin/python3 ./mach build

      - name: End sccache session
        run: sleep 60 && $HOME/.mozbuild/sccache/sccache --stop-server

      - name: Export the DMG image
        run: /usr/bin/python3 ./mach package
      
      - name: Saving sccache
        id: save-sccache-cache
        if: always()
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          key: ${{ runner.os }}-ld64-${{ github.run_id }}
          path: ~/Library/Caches/Mozilla.sccache
      
      - name: Polyfill & Repackage
        id: polyfill-and-repkg
        run: |
          export VERSION=$(cat browser/config/version_display.txt)

          hdiutil attach -noverify "obj-ff-dbg-esr/dist/momizu-${VERSION}.en-US.mac.dmg"  
          cp -R /Volumes/Momizu-Preview/Momizu-Preview.app /tmp        

          # Build libMacportsLegacySystem.B.dylib (patched to support CCRandomGenerateBytes and exp10)
          git clone --recursive --branch 1.5.2_addCCRandom https://github.com/aobaharuki2005/macports-legacy-support.git
          cd macports-legacy-support

          CC="clang --target=x86_64-apple-macos10.6" \
          CXX="clang++ --target=x86_64-apple-macos10.6" \
          CFLAGS="-Os" \
          CXXFLAGS="-Os" \
          LDFLAGS="--target=x86_64-apple-macos10.6" \
          make

          cp lib/libMacportsLegacySystem.B.dylib /tmp/Momizu-Preview.app/Contents/MacOS
          cd /tmp/Momizu-Preview.app/Contents/MacOS/

          # On macOS 10.7, CoreText.framework is located inside ApplicationServices.framework, so we need to polyfill it in XUL
          install_name_tool -change "/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText" "/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices" "XUL"

          # Polyfill XUL, libmozavutil.dylib and libgkcodecs.dylib
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "XUL"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libmozavutil.dylib"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libgkcodecs.dylib"

          # Package the output app
          cd /tmp
          zip -qr "Momizu-Preview-${VERSION}_macOS10.7-10.8.zip" Momizu-Preview.app
      
      - name: Upload Momizu-Preview for macOS 10.7-10.8 build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          archive: false
          path: /tmp/*.zip
          if-no-files-found: error
          retention-days: 7

  macos1009-1011:
    name: build for macOS 10.9-10.11
    runs-on: macos-15
    if: ${{ !endsWith(github.event.head_commit.message, 'DONTBUILD') && !contains(github.event.head_commit.message, 'IGNORE10091011') && contains(github.event.head_commit.message, 'BUILDMOMIZU') }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          submodules: true
      
      - name: Restore cached sccache
        id: restore-sccache-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/Library/Caches/Mozilla.sccache 
          key: ${{ runner.os }}-lld-1009-1011-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-lld-1009-1011
      
      - name: Restore cached mozbuild toolchains
        id: restore-mozbuild-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/.mozbuild
          key: ${{ runner.os }}-mozbuild-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-mozbuild-
      
      - name: Bootstrap build deps
        id: bootstrap-build-deps
        run: |
          if [ ! -d "$HOME/.mozbuild" ]; then
            echo "Cached .mozbuild toolchain not found. Starting bootstrap..."
            /usr/bin/python3 ./mach bootstrap --application-choice=browser
        
            # Create temp folder to save necessary toolchains
            mkdir -p ~/tmp_toolchains
            
            # Move necessary toolchains outside
            [ -d "$HOME/.mozbuild/node" ] && mv "$HOME/.mozbuild/node" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sccache" ] && mv "$HOME/.mozbuild/sccache" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/cbindgen" ] && mv "$HOME/.mozbuild/cbindgen" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/clang" ] && mv "$HOME/.mozbuild/clang" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sysroot-wasm32-wasi" ] && mv "$HOME/.mozbuild/sysroot-wasm32-wasi" ~/tmp_toolchains/
            
            # Purge old .mozbuild
            rm -rf "$HOME/.mozbuild"
        
            # Rename to (new) .mozbuild
            mv ~/tmp_toolchains "$HOME/.mozbuild"
            
            # echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, nasm, dump_syms, clang, sysroot-wasm32-wasi"
            echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, clang, sysroot-wasm32-wasi"
          fi

          # Install nasm from Homebrew
          brew install nasm
      
      - name: Bootstrap Rust toolchain
        id: bootstrap-rust
        run: |
          export RUST_VERSION=1.82.0
          if [ ! -d "$HOME/.rustup/toolchains/${RUST_VERSION}-custom-aarch64" ]; then
            echo "Cached Rust ${RUST_VERSION}-custom-aarch64 not found. Starting bootstrap..."
            curl -L https://github.com/aobaharuki2005/rust/releases/download/${RUST_VERSION}-custom/${RUST_VERSION}-custom-aarch64.zip -o ${RUST_VERSION}-custom-aarch64.zip
            mkdir -p ~/.rustup/toolchains
            unzip -q ${RUST_VERSION}-custom-aarch64.zip -d ~/.rustup/toolchains
            echo "Bootstrap Rust ${RUST_VERSION}-custom-aarch64 finished."
          fi
        
          # Change default Rust toolchain
          rustup default ${RUST_VERSION}-custom-aarch64
          rustup override set ${RUST_VERSION}-custom-aarch64

          # Verify Rust installation
          cargo --version
          rustc --version
      
      - name: Create mozconfig build config from template
        run: ln -sf ./mozconfig-cicd_1009-1011-momizu.sh .mozconfig
      
      - name: Configure build options
        run: /usr/bin/python3 ./mach configure

      - name: Build
        run: /usr/bin/python3 ./mach build

      - name: End sccache session
        run: sleep 60 && $HOME/.mozbuild/sccache/sccache --stop-server

      - name: Export the DMG image
        run: /usr/bin/python3 ./mach package
      
      - name: Saving sccache
        id: save-sccache-cache
        if: always()
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          key: ${{ runner.os }}-lld-1009-1011-${{ github.run_id }}
          path: ~/Library/Caches/Mozilla.sccache
      
      - name: Polyfill & Repackage
        id: polyfill-and-repkg
        run: |
          # Get the current Momiji version
          export VERSION=$(cat browser/config/version_display.txt)

          hdiutil attach -noverify "obj-ff-dbg-esr/dist/momizu-${VERSION}.en-US.mac.dmg"  
          cp -R /Volumes/Momizu-Preview/Momizu-Preview.app /tmp       

          # Build libMacportsLegacySystem.B.dylib (patched to support CCRandomGenerateBytes and exp10)
          git clone --recursive --branch 1.5.2_addCCRandom https://github.com/aobaharuki2005/macports-legacy-support.git
          cd macports-legacy-support

          CC="clang --target=x86_64-apple-macos10.6" \
          CXX="clang++ --target=x86_64-apple-macos10.6" \
          CFLAGS="-Os" \
          CXXFLAGS="-Os" \
          LDFLAGS="--target=x86_64-apple-macos10.6" \
          make

          cp lib/libMacportsLegacySystem.B.dylib /tmp/Momizu-Preview.app/Contents/MacOS
           cd /tmp/Momizu-Preview.app/Contents/MacOS/
          
          # Polyfill XUL, libmozavutil.dylib and libgkcodecs.dylib
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "XUL"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libmozavutil.dylib"
          install_name_tool -change "/usr/lib/libSystem.B.dylib" "@executable_path/libMacportsLegacySystem.B.dylib" "libgkcodecs.dylib"

          # Package the output app
          cd /tmp
          zip -qr "Momizu-Preview-${VERSION}_macOS10.9-10.11.zip" Momizu-Preview.app
      
      - name: Upload Momizu-Preview for macOS 10.9-10.11 build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          archive: false
          path: /tmp/*.zip
          if-no-files-found: error
          retention-days: 7

  macos1012-1014:
    name: build for macOS 10.12-10.14
    runs-on: macos-15
    if: ${{ !endsWith(github.event.head_commit.message, 'DONTBUILD') && !contains(github.event.head_commit.message, 'IGNORE10121014') && contains(github.event.head_commit.message, 'BUILDMOMIZU') }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          submodules: true
      
      - name: Restore cached sccache
        id: restore-sccache-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/Library/Caches/Mozilla.sccache 
          key: ${{ runner.os }}-lld-1012-1014-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-lld-1012-1014
      
      - name: Restore cached mozbuild toolchains
        id: restore-mozbuild-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          path: ~/.mozbuild
          key: ${{ runner.os }}-mozbuild-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-mozbuild-
            
      - name: Bootstrap build deps
        id: bootstrap-build-deps
        run: |
          if [ ! -d "$HOME/.mozbuild" ]; then
            echo "Cached .mozbuild toolchain not found. Starting bootstrap..."
            /usr/bin/python3 ./mach bootstrap --application-choice=browser
        
            # Create temp folder to save necessary toolchains
            mkdir -p ~/tmp_toolchains
            
            # Move necessary toolchains outside
            [ -d "$HOME/.mozbuild/node" ] && mv "$HOME/.mozbuild/node" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sccache" ] && mv "$HOME/.mozbuild/sccache" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/cbindgen" ] && mv "$HOME/.mozbuild/cbindgen" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/clang" ] && mv "$HOME/.mozbuild/clang" ~/tmp_toolchains/
            [ -d "$HOME/.mozbuild/sysroot-wasm32-wasi" ] && mv "$HOME/.mozbuild/sysroot-wasm32-wasi" ~/tmp_toolchains/
            
            # Purge old .mozbuild
            rm -rf "$HOME/.mozbuild"
        
            # Rename to (new) .mozbuild
            mv ~/tmp_toolchains "$HOME/.mozbuild"
            
            # echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, nasm, dump_syms, clang, sysroot-wasm32-wasi"
            echo "Bootstrap finished. Kept: nodejs, sccache, cbindgen, clang, sysroot-wasm32-wasi"
          fi

          # Install nasm from Homebrew
          brew install nasm
    
      - name: Bootstrap Rust toolchain
        id: bootstrap-rust
        run: |
          rustup install nightly-2025-01-09   # v1.86.0-nightly
          rustup default nightly-2025-01-09   
          rustup override set nightly-2025-01-09

          # Add support for cross compiling for x86_64-apple-darwin target
          rustup target add x86_64-apple-darwin

          # Verify Rust installation
          cargo --version
          rustc --version
      
      - name: Create mozconfig build config from template
        run: ln -sf ./mozconfig-cicd_1012-1014-momizu.sh .mozconfig
      
      - name: Configure build options
        run: /usr/bin/python3 ./mach configure

      - name: Build
        run: /usr/bin/python3 ./mach build

      - name: End sccache session
        run: sleep 60 && $HOME/.mozbuild/sccache/sccache --stop-server

      - name: Export the DMG image
        run: /usr/bin/python3 ./mach package
      
      - name: Polyfill & Repackage
        id: polyfill-and-repkg
        run: |
          # Get the current Momiji version
          export VERSION=$(cat browser/config/version_display.txt)

          hdiutil attach -noverify "obj-ff-dbg-esr/dist/momizu-${VERSION}.en-US.mac.dmg"  
          cp -R /Volumes/Momizu-Preview/Momizu-Preview.app /tmp        
          cd /tmp
          zip -qr "Momizu-Preview-${VERSION}_macOS10.12-10.14.zip" Momizu-Preview.app
      
      - name: Saving sccache
        id: save-sccache-cache
        if: always()
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5.0.4
        with:
          key: ${{ runner.os }}-lld-1012-1014-${{ github.run_id }}
          path: ~/Library/Caches/Mozilla.sccache
    
      - name: Upload Momizu-Preview for macOS 10.12-10.14 build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          archive: false
          path: /tmp/*.zip
          if-no-files-found: error
          retention-days: 7

      
        
      
